apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hermes
  labels:
    app: hermes
spec:
  selector:
    matchLabels:
      app: hermes-metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s