apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes.fullname" . }}-secrets
type: Opaque
stringData:
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  {{- end }}
  {{- range $name, $url := .Values.secrets.slackWebhooks }}
  destination-{{ $name }}-webhook-url: {{ $url | quote }}
  {{- end }}
  {{- range $name, $url := .Values.secrets.discordWebhooks }}
  destination-{{ $name }}-webhook-url: {{ $url | quote }}
  {{- end }}
